import type { Metadata } from "next";
import "./globals.css";
import { fonts } from "./fonts";
import { ColorModeScript } from "@chakra-ui/react";
import StoreProvider from "./StoreProvider";
import "@vidstack/react/player/styles/default/theme.css";
import "@vidstack/react/player/styles/default/layouts/video.css";
import videojs from "video.js";
import "video.js/dist/video-js.css";
import "./videojs-custom-headers.js";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={fonts.inter.className}>
      <body>
        <ColorModeScript initialColorMode={"light"} />

        <StoreProvider>{children}</StoreProvider>
      </body>
    </html>
  );
}
